/// <reference types="node" />
import esbuild from "esbuild";
import process from "process";
import inlineImportPlugin from "esbuild-plugin-inline-import";
import fs from "fs"
import { spawnSync } from "child_process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const args = {
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/closebrackets",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/comment",
		"@codemirror/fold",
		"@codemirror/gutter",
		"@codemirror/highlight",
		"@codemirror/history",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/matchbrackets",
		"@codemirror/panel",
		"@codemirror/rangeset",
		"@codemirror/rectangular-selection",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/stream-parser",
		"@codemirror/text",
		"@codemirror/tooltip",
		"@codemirror/view",
		"@lezer/highlight",
		"@lezer/common",
		"@lezer/lr",
		"fs",
		"path",
		"os",
		],
	format: "cjs",
	target: "es2016",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	minify: prod,
	treeShaking: true,
	outfile: "main.js",
	plugins: [
		inlineImportPlugin()
	]
};

function debouncer(func, wait) {
	let timeout;
	return function(...args) {
		const context = this;
		clearTimeout(timeout);
		timeout = setTimeout(() => func.apply(context, args), wait);
	};
}

if (!prod) {
	const ctx = await esbuild.context(args);
	ctx.watch().catch(() => process.exit(1));
	const debouncedExec = debouncer((eventType, filename) => {
		if (filename.endsWith(".grammar")) {
			console.log(`Detected change in ${filename}, rebuilding...`);
			const result = spawnSync("npm", ["run", "generator"], { shell: true, stdio: "inherit" });
			if (result.toString().trim() !== "") {
				console.log(result.toString());
			}
		}
	}, 5000);
	fs.watch("src/parser", { recursive: true }, debouncedExec);	
}
else {
	const meta_args = {...args, metafile: true };
	esbuild.build(meta_args).catch(() => process.exit(1)).then((result) => {
		esbuild.analyzeMetafile(result.metafile, { verbose: true }).then((analysis) => {
			console.log(analysis);
		});
	})
}
