/// <reference types="node" />
import esbuild from "esbuild";
import process from "process";
import inlineImportPlugin from "esbuild-plugin-inline-import";
import fs from "fs"
import { spawnSync } from "child_process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const test = (process.argv[2] === "test");
const dev = !prod && !test;
const args = {
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/closebrackets",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/comment",
		"@codemirror/fold",
		"@codemirror/gutter",
		"@codemirror/highlight",
		"@codemirror/history",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/matchbrackets",
		"@codemirror/panel",
		"@codemirror/rangeset",
		"@codemirror/rectangular-selection",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/stream-parser",
		"@codemirror/text",
		"@codemirror/tooltip",
		"@codemirror/view",
		"@lezer/highlight",
		"@lezer/common",
		"@lezer/lr",
		"i18next",
		"fs",
		"path",
		"os",
	],
	format: "cjs",
	target: "es2016",
	logLevel: "info",
	sourcemap: prod ? false : "inline" as const,
	minify: prod,
	treeShaking: true,
	outfile: "main.js",
	plugins: [
		inlineImportPlugin()
	],
} satisfies esbuild.BuildOptions;

function debouncer<A, R>(func: (...args: A[]) => R, wait: number) {
	let timeout: NodeJS.Timeout;
	return function(...args: A[]) {
		clearTimeout(timeout);
		timeout = setTimeout(() => func(...args), wait);
	};
}

if (dev) {
	const ctx = await esbuild.context(args);
	ctx.watch().catch(() => process.exit(1));
	const debouncedExec = debouncer((eventType, filename: string | null) => {
		if (filename === null) return;
		if (filename.endsWith(".grammar")) {
			console.log(`Detected change in ${filename}, rebuilding...`);
			const result = spawnSync("npm", ["run", "generator:latex"], { shell: true, stdio: "inherit" });
			if (result.toString().trim() !== "") {
				console.log(result.toString());
			}
		}
	}, 5000);
	fs.watch("src/parser", { recursive: true }, debouncedExec);	
} else if (prod) {
	esbuild.build(args).catch(() => process.exit(1));
} else if (test) {
	args.entryPoints = ["tests/main.ts"]
	args.outfile = "dist/dev/main.js"
	fs.copyFileSync("manifest.json", "dist/dev/manifest.json");
	await esbuild.build(args).catch(() => process.exit(1));
}
