// Taken from vimtex
// https://github.com/lervag/vimtex/blob/master/autoload/vimtex/syntax/core.vim


export const cmd_symbols:{[name:string]: string} =
{
	"aleph": "ℵ",
	"amalg": "⨿",
	"And": "&",
	"angle": "∠",
	"approx": "≈",
	"approxeq": "≊",
	"ast": "∗",
	"asymp": "≍",
	"backepsilon": "∍",
	"backprime": "‵",
	"backsim": "∽",
	"backsimeq": "⋍",
	"backslash": "∖",
	"barwedge": "⊼",
	"Bbbk": "k",
	"because": "∵",
	"beth": "ℶ",
	"between": "≬",
	"bigcap": "⋂",
	"bigcirc": "◯",
	"bigcup": "⋃",
	"bigodot": "⨀",
	"bigoplus": "⨁",
	"bigotimes": "⨂",
	"bigsqcup": "⨆",
	"bigstar": "★",
	"bigtriangledown": "▽",
	"bigtriangleup": "△",
	"biguplus": "⨄",
	"bigvee": "⋁",
	"bigwedge": "⋀",
	"blacklozenge": "⧫",
	"blacksquare": "◼",
	"blacktriangle": "▴",
	"blacktriangledown": "▾",
	"blacktriangleleft": "◂",
	"blacktriangleright": "▸",
	"bot": "⊥",
	"bowtie": "⋈",
	"Box": "◻",
	"boxdot": "⊡",
	"boxminus": "⊟",
	"boxplus": "⊞",
	"boxtimes": "⊠",
	"bullet": "∙",
	"bumpeq": "≏",
	"Bumpeq": "≎",
	"Cap": "⋒",
	"cap": "∩",
	"cdot": "⋅",
	"cdotp": "⋅",
	"cdots": "⋯",
	"celsius": "℃",
	"centerdot": "⋅",
	"checkmark": "✓",
	"circ": "∘",
	"circeq": "≗",
	"circlearrowleft": "↺",
	"circlearrowright": "↻",
	"circledast": "⊛",
	"circledcirc": "⊚",
	"circleddash": "⊝",
	"circledR": "®",
	"circledS": "Ⓢ",
	"clubsuit": "♣",
	"complement": "∁",
	"cong": "≅",
	"coprod": "∐",
	"copyright": "©",
	"cp": "×",
	"cross": "×",
	"crossproduct": "×",
	"Cup": "⋓",
	"cup": "∪",
	"curlyeqprec": "⋞",
	"curlyeqsucc": "⋟",
	"curlyvee": "⋎",
	"curlywedge": "⋏",
	"curvearrowleft": "↶",
	"curvearrowright": "↷",
	"dagger": "†",
	"daleth": "ℸ",
	"dashleftarrow": "⇠",
	"dashrightarrow": "⇢",
	"dashv": "⊣",
	"ddagger": "‡",
	"ddots": "⋱",
	"degree": "°",
	"diagdown": "╲",
	"diagup": "╱",
	"Diamond": "◊",
	"diamond": "⋄",
	"diamondsuit": "♢",
	"digamma": "ϝ",
	"div": "÷",
	"divideontimes": "⋇",
	"divsymbol": "÷",
	"Doteq": "≑",
	"doteq": "≐",
	"doteqdot": "≑",
	"dotplus": "∔",
	"dotproduct": "⋅",
	"dots": "…",
	"dotsb": "⋯",
	"dotsc": "…",
	"dotsi": "⋯",
	"dotsm": "⋯",
	"dotso": "…",
	"doublebarwedge": "⩞",
	"doublecap": "⋒",
	"doublecup": "⋓",
	"downarrow": "↓",
	"Downarrow": "⇓",
	"downdownarrows": "⇊",
	"downharpoonleft": "⇃",
	"downharpoonright": "⇂",
	"ell": "ℓ",
	"emptyset": "∅",
	"eqcirc": "≖",
	"eqsim": "≂",
	"eqslantgtr": "⪖",
	"eqslantless": "⪕",
	"equiv": "≡",
	"eth": "ð",
	"exists": "∃",
	"fallingdotseq": "≒",
	"Finv": "Ⅎ",
	"flat": "♭",
	"forall": "∀",
	"frown": "⌢",
	"Game": "⅁",
	"ge": "≥",
	"geq": "≥",
	"geqq": "≧",
	"geqslant": "⩾",
	"gets": "←",
	"gg": "≫",
	"ggg": "⋙",
	"gggtr": "⋙",
	"gimel": "ℷ",
	"gnapprox": "⪊",
	"gneq": "⪈",
	"gneqq": "≩",
	"gnsim": "⋧",
	"gradientnabla": "∇",
	"gt": ">",
	"gtrapprox": "⪆",
	"gtrdot": "⋗",
	"gtreqless": "⋛",
	"gtreqqless": "⪌",
	"gtrless": "≷",
	"gtrsim": "≳",
	"gvertneqq": "≩",
	"hbar": "ℏ",
	"heartsuit": "♡",
	"hookleftarrow": "↩",
	"hookrightarrow": "↪",
	"hslash": "ℏ",
	"iff": "⇔",
	"iiiint": "⨌",
	"iiint": "∭",
	"iint": "∬",
	"Im": "ℑ",
	"imaginary": "ℑ",
	"imath": "ı",
	"in": "∈",
	"infty": "∞",
	"injlim": "inj lim",
	"int": "∫",
	"intercal": "⊺",
	"intop": "∫",
	"jmath": "ȷ",
	"Join": "⋈",
	"land": "∧",
	"lceil": "⌈",
	"ldotp": ".",
	"ldots": "…",
	"le": "≤",
	"leadsto": "⇝",
	"left": "",
	"Leftarrow": "⇐",
	"leftarrow": "←",
	"leftarrowtail": "↢",
	"leftharpoondown": "↽",
	"leftharpoonup": "↼",
	"leftleftarrows": "⇇",
	"Leftrightarrow": "⇔",
	"leftrightarrow": "↔",
	"leftrightarrows": "⇆",
	"leftrightharpoons": "⇋",
	"leftrightsquigarrow": "↭",
	"leftthreetimes": "⋋",
	"leq": "≤",
	"leqq": "≦",
	"leqslant": "⩽",
	"lessapprox": "⪅",
	"lessdot": "⋖",
	"lesseqgtr": "⋚",
	"lesseqqgtr": "⪋",
	"lessgtr": "≶",
	"lesssim": "≲",
	"lhd": "⊲",
	"ll": "≪",
	"Lleftarrow": "⇚",
	"lll": "⋘",
	"llless": "⋘",
	// "lmoustache": "╭",
	"lnapprox": "⪉",
	"lneq": "⪇",
	"lneqq": "≨",
	"lnot": "¬",
	"lnsim": "⋦",
	"longleftarrow": "⟵",
	"Longleftarrow": "⟸",
	"Longleftrightarrow": "⟺",
	"longleftrightarrow": "⟷",
	"longmapsto": "⟼",
	"longrightarrow": "⟶",
	"Longrightarrow": "⟹",
	"looparrowleft": "↫",
	"looparrowright": "↬",
	"lor": "∨",
	"lozenge": "◊",
	"Lsh": "↰",
	"lt": "<",
	"ltimes": "⋉",
	"lvertneqq": "≨",
	"maltese": "✠",
	"mapsto": "↦",
	"measuredangle": "∡",
	"mho": "℧",
	"micro": "µ",
	"mid": "∣",
	"middle": "",
	"models": "⊨",
	"mp": "∓",
	"multimap": "⊸",
	"nabla": "∇",
	"natural": "♮",
	"ncong": "≇",
	"ne": "≠",
	"nearrow": "↗",
	"neg": "¬",
	"neq": "≠",
	"neqslant": "≠",
	"nexists": "∄",
	"ngeq": "≱",
	"ngeqq": "≱",
	"ngeqslant": "⪈",
	"ngtr": "≯",
	"ni": "∋",
	"nleftarrow": "↚",
	"nLeftarrow": "⇍",
	"nleftrightarrow": "↮",
	"nLeftrightarrow": "⇎",
	"nleq": "≰",
	"nleqq": "≰",
	"nleqslant": "⪇",
	"nless": "≮",
	"nmid": "∤",
	"notChar": "⧸",
	"notin": "∉",
	"nparallel": "∦",
	"nprec": "⊀",
	"npreceq": "⋠",
	"nrightarrow": "↛",
	"nRightarrow": "⇏",
	"nshortmid": "∤",
	"nshortparallel": "∦",
	"nsim": "≁",
	"nsubseteq": "⊈",
	"nsubseteqq": "⊈",
	"nsucc": "⊁",
	"nsucceq": "⋡",
	"nsupseteq": "⊉",
	"nsupseteqq": "⊉",
	"ntriangleleft": "⋪",
	"ntrianglelefteq": "⋬",
	"ntriangleright": "⋫",
	"ntrianglerighteq": "⋭",
	"nvdash": "⊬",
	"nvDash": "⊭",
	"nVdash": "⊮",
	"nVDash": "⊯",
	"nwarrow": "↖",
	"odot": "⊙",
	"ohm": "Ω",
	"oint": "∮",
	"ominus": "⊖",
	"oplus": "⊕",
	"oslash": "⊘",
	"otimes": "⊗",
	"owns": "∋",
	"P": "¶",
	"parallel": "∥",
	"partial": "∂",
	"perp": "⊥",
	"perthousand": "‰",
	"pitchfork": "⋔",
	"pm": "±",
	"prec": "≺",
	"precapprox": "⪷",
	"preccurlyeq": "≼",
	"preceq": "⪯",
	"precnapprox": "⪹",
	"precneqq": "⪵",
	"precnsim": "⋨",
	"precsim": "≾",
	"prime": "′",
	"prod": "∏",
	"projlim": "proj lim",
	"propto": "∝",
	"qquad": " ",
	"quad": " ",
	"rceil": "⌉",
	"Re": "ℜ",
	"real": "ℜ",
	"restriction": "↾",
	"rhd": "⊳",
	"right": "",
	"Rightarrow": "⇒",
	"rightarrow": "→",
	"rightarrowtail": "↣",
	"rightharpoondown": "⇁",
	"rightharpoonup": "⇀",
	"rightleftarrows": "⇄",
	"rightleftharpoons": "⇌",
	"rightrightarrows": "⇉",
	"rightsquigarrow": "⇝",
	"rightthreetimes": "⋌",
	"risingdotseq": "≓",
	// "rmoustache": "╮",
	"Rrightarrow": "⇛",
	"Rsh": "↱",
	"rtimes": "⋊",
	"S": "§",
	"searrow": "↘",
	"setminus": "∖",
	"sharp": "♯",
	"shortmid": "∣",
	"shortparallel": "∥",
	"sim": "∼",
	"simeq": "≃",
	"smallfrown": "⌢",
	"smallint": "∫",
	"smallsetminus": "∖",
	"smallsmile": "⌣",
	"smile": "⌣",
	"spadesuit": "♠",
	"sphericalangle": "∢",
	"sqcap": "⊓",
	"sqcup": "⊔",
	"sqsubset": "⊏",
	"sqsubseteq": "⊑",
	"sqsupset": "⊐",
	"sqsupseteq": "⊒",
	"square": "◻",
	"star": "⋆",
	"Subset": "⋐",
	"subset": "⊂",
	"subseteq": "⊆",
	"subseteqq": "⫅",
	"subsetneq": "⊊",
	"subsetneqq": "⫋",
	"succ": "≻",
	"succapprox": "⪸",
	"succcurlyeq": "≽",
	"succeq": "⪰",
	"succnapprox": "⪺",
	"succneqq": "⪶",
	"succnsim": "⋩",
	"succsim": "≿",
	"sum": "∑",
	"Supset": "⋑",
	"supset": "⊃",
	"supseteq": "⊇",
	"supseteqq": "⫆",
	"supsetneq": "⊋",
	"supsetneqq": "⫌",
	"surd": "√",
	"swarrow": "↙",
	"therefore": "∴",
	"thickapprox": "≈",
	"thicksim": "∼",
	"times": "×",
	"to": "→",
	"top": "⊤",
	"triangle": "△",
	"triangledown": "▽",
	"triangleleft": "◃",
	"trianglelefteq": "⊴",
	"triangleq": "≜",
	"triangleright": "▹",
	"trianglerighteq": "⊵",
	"twoheadleftarrow": "↞",
	"twoheadrightarrow": "↠",
	"unlhd": "⊴",
	"unrhd": "⊵",
	"uparrow": "↑",
	"Uparrow": "⇑",
	"updownarrow": "↕",
	"Updownarrow": "⇕",
	"upharpoonleft": "↿",
	"upharpoonright": "↾",
	"uplus": "⊎",
	"upuparrows": "⇈",
	"varpropto": "∝",
	"varsubsetneq": "⊊",
	"varsubsetneqq": "⫋",
	"varsupsetneq": "⊋",
	"varsupsetneqq": "⫌",
	"vartriangle": "△",
	"vartriangleleft": "⊲",
	"vartriangleright": "⊳",
	"vDash": "⊨",
	"Vdash": "⊩",
	"vdash": "⊢",
	"vdot": "⋅",
	"vdots": "⋮",
	"vee": "∨",
	"veebar": "⊻",
	"Vvdash": "⊪",
	"wedge": "∧",
	"wp": "℘",
	"wr": "≀",
	"yen": "¥",
	"implies": "⇒",
	"impliedby": "⇐",
	"choose": "C",
	"sqrt": "√",
	"coloneqq": "≔",
	"colon": ":",
	"Colonapprox": "::≈",
	"Coloneq": "::-",
	"Coloneqq": "⩴",
	"Colonsim": "::∼",
	"Eqcolon": "-::",
	"Eqqcolon": "=::",
	"colonapprox": ":≈",
	"coloneq": ":-",
	"colonsim": ":∼",
	"dblcolon": "∷",
	"eqcolon": "∹",
	"eqqcolon": "≕",

	"displaystyle": " ",
	",": " ",
	":": " ",
	";": " ",
	">": " ",
	"enspace": " ",
	"thinspace": " ",
	"negthinspace": "",
	"!": "",

	"textacutedbl": "˝",
	"textasciiacute": "´",
	"textasciibreve": "˘",
	"textasciicaron": "ˇ",
	"textasciicircum": "^",
	"textasciidieresis": "¨",
	"textasciimacron": "¯",
	"textasciitilde": "~",
	"textasteriskcentered": "*",
	"textbackslash": "\\",
	"textbaht": "฿",
	"textbar": "|",
	"textbardbl": "‖",
	"textbigcircle": "◯",
	"textblank": "␢",
	"textborn": "*",
	"textbraceleft": "{",
	"textbraceright": "}",
	"textbrokenbar": "¦",
	"textbullet": "•",
	"textcelsius": "℃",
	"textcent": "¢",
	"textcentoldstyle": "¢",
	"textcircledP": "℗",
	"textcolonmonetary": "₡",
	"textcompwordmark": "‌",
	"textcopyleft": "🄯",
	"textcopyright": "©",
	"textcurrency": "¤",
	"textdagger": "†",
	"textdaggerdbl": "‡",
	"textdegree": "°",
	"textdied": "†",
	"textdiscount": "⁒",
	"textdiv": "÷",
	"textdivorced": "⚮",
	"textdollar": "$",
	"textdollaroldstyle": "$",
	"textdong": "₫",
	"textdownarrow": "↓",
	"texteightoldstyle": "8",
	"textellipsis": "…",
	"textemdash": "—",
	"textendash": "–",
	"textestimated": "℮",
	"texteuro": "€",
	"textexclamdown": "¡",
	"textfiveoldstyle": "5",
	"textflorin": "ƒ",
	"textfouroldstyle": "4",
	"textfractionsolidus": "⁄",
	"textgravedbl": "˵",
	"textgreater": ">",
	"textguarani": "₲",
	"textinterrobang": "‽",
	"textinterrobangdown": "⸘",
	"textlangle": "〈",
	"textlbrackdbl": "⟦",
	"textleftarrow": "←",
	"textless": "<",
	"textlira": "₤",
	"textlnot": "¬",
	"textlquill": "⁅",
	"textmarried": "⚭",
	"textmho": "℧",
	"textminus": "−",
	"textmu": "µ",
	"textmusicalnote": "♪",
	"textnaira": "₦",
	"textnineoldstyle": "9",
	"textnumero": "№",
	"textohm": "Ω",
	"textonehalf": "½",
	"textoneoldstyle": "1",
	"textonequarter": "¼",
	"textonesuperior": "¹",
	"textopenbullet": "◦",
	"textordfeminine": "ª",
	"textordmasculine": "º",
	"textparagraph": "¶",
	"textperiodcentered": "·",
	"textpertenthousand": "‱",
	"textperthousand": "‰",
	"textpeso": "₱",
	"textpm": "±",
	"textquestiondown": "¿",
	"textquotedblleft": "“",
	"textquotedblright": "”",
	"textquoteleft": "‘",
	"textquoteright": "’",
	"textrangle": "〉",
	"textrbrackdbl": "⟧",
	"textrecipe": "℞",
	"textreferencemark": "※",
	"textregistered": "®",
	"textrightarrow": "→",
	"textrquill": "⁆",
	"textsection": "§",
	"textservicemark": "℠",
	"textsevenoldstyle": "7",
	"textsixoldstyle": "6",
	"textsterling": "£",
	"textsurd": "√",
	"textthreeoldstyle": "3",
	"textthreequarters": "¾",
	"textthreesuperior": "³",
	"texttildelow": "˷",
	"texttimes": "×",
	"texttrademark": "™",
	"texttwooldstyle": "2",
	"texttwosuperior": "²",
	"textunderscore": "_",
	"textuparrow": "↑",
	"textvisiblespace": "␣",
	"textwon": "₩",
	"textyen": "¥",
	"textzerooldstyle": "0",
};

export const not_remap: Record<string, string> = {
	"leftarrow": "↚",
	"to": "↛",
	"leftrightarrow": "↮",
	"Leftarrow": "⇍",
	"Rightarrow": "⇏",
	"Leftrightarrow": "⇎",
	"in": "∉",
	"owns": "∌",
	"shortmid": "∤",
	"shortparallel": "∦",
	"thicksim": "≁",
	"simeq": "≄",
	"cong": "≇",
	"thickapprox": "≉",
	"asymp": "≭",
	"equiv": "≢",
	"lt": "≮",
	"gt": "≯",
	"leq": "≰",
	"geq": "≱",
	"lesssim": "≴",
	"gtrsim": "≵",
	"lessgtr": "≸",
	"gtrless": "≹",
	"prec": "⊀",
	"succ": "⊁",
	"subset": "⊄",
	"supset": "⊅",
	"subseteq": "⊈",
	"supseteq": "⊉",
	"vdash": "⊬",
	"vDash": "⊭",
	"Vdash": "⊮",
	"preccurlyeq": "⋠",
	"succcurlyeq": "⋡",
	"sqsubseteq": "⋢",
	"sqsupseteq": "⋣",
	"vartriangleleft": "⋪",
	"vartriangleright": "⋫",
	"unlhd": "⋬",
	"unrhd": "⋭",
	"exists": "∄",
}


export const operators:string[] =
// From https://www.overleaf.com/learn/latex/Operators
[
	"arcsin",
	"arccos",
	"arctan",
	"sinh",
	"cosh",
	"tanh",
	"coth",
	"sin",
	"cos",
	"tan",
	"sec",
	"csc",
	"cot",
	"exp",
	"ker",
	"limsup",
	"lim",
	"sup",
	"deg",
	"gcd",
	"log",
	"lg",
	"ln",
	"Pr",
	"det",
	"hom",
	"arg",
	"dim",
	"liminf",
	"min",
	"max",
	"inf",
	"mod",

	];


export const fractions: { [name: string]: string } = {
	"{1}{2}": "½",
	"{1}{3}": "⅓",
	"{2}{3}": "⅔",
	"{1}{4}": "¼",
	"{1}{5}": "⅕",
	"{2}{5}": "⅖",
	"{3}{5}": "⅗",
	"{4}{5}": "⅘",
	"{1}{6}": "⅙",
	"{5}{6}": "⅚",
	"{1}{8}": "⅛",
	"{3}{8}": "⅜",
	"{5}{8}": "⅝",
	"{7}{8}": "⅞",
};


export const greek:{[name: string]:string} =
{
	"alpha":      "α",
	"beta":       "β",
	"gamma":      "γ",
	"varGamma": "Γ",
	"delta":      "δ",
	"varDelta": "Δ",
	"epsilon":    "ϵ",
	"varepsilon": "ε",
	"zeta":       "ζ",
	"eta":        "η",
	"theta":      "θ",
	"vartheta":   "ϑ",
	"iota":       "ι",
	"kappa":      "κ",
	"varkappa": "ϰ",
	"lambda":     "λ",
	"mu":         "μ",
	"nu":         "ν",
	"xi":         "ξ",
	"omicron": "ο",
	"pi":         "π",
	"varpi":      "ϖ",
	"varPi": "Π",
	"rho":        "ρ",
	"varrho":     "ϱ",
	"sigma":      "σ",
	"varsigma":   "ς",
	"varSigma": "Σ",
	"tau":        "τ",
	"upsilon":    "υ",
	"phi":        "ϕ",
	"varphi":     "φ",
	"varPhi": "Φ",
	"chi":        "χ",
	"psi":        "ψ",
	"varPsi": "Ψ",
	"omega":      "ω",
	"Gamma":      "Γ",
	"Delta":      "Δ",
	"Theta":      "Θ",
	"varTheta": "Θ",
	"Lambda":     "Λ",
	"varLambda": "Λ",
	"Xi":         "Ξ",
	"varXi": "Ξ",
	"Pi":         "Π",
	"Sigma":      "Σ",
	"Upsilon":    "Υ",
	"varUpsilon": "Υ",
	"Phi":        "Φ",
	"Chi":        "Χ",
	"Psi":        "Ψ",
	"Omega":      "Ω",
	"varOmega": "Ω",
	"varnothing": "∅",

	"upalpha": "α",
	"upbeta": "β",
	"upgamma": "γ",
	"updelta": "δ",
	"upepsilon": "ϵ",
	"upzeta": "ζ",
	"upeta": "η",
	"uptheta": "θ",
	"upiota": "ι",
	"upkappa": "κ",
	"uplambda": "λ",
	"upmu": "μ",
	"upnu": "ν",
	"upxi": "ξ",
	"upomicron": "ο",
	"uppi": "π",
	"uprho": "ρ",
	"upsigma": "σ",
	"uptau": "τ",
	"upupsilon": "υ",
	"upphi": "ϕ",
	"upchi": "χ",
	"uppsi": "ψ",
	"upomega": "ω",
	"upvarepsilon": "ε",
	"upvartheta": "ϑ",
	"upvarpi": "ϖ",
	"upvarrho": "ϱ",
	"upvarsigma": "ς",
	"upvarphi": "φ",
	"Upgamma": "Γ",
	"Updelta": "Δ",
	"Uptheta": "Θ",
	"Uplambda": "Λ",
	"Upxi": "Ξ",
	"Uppi": "Π",
	"Upsigma": "Σ",
	"Upupsilon": "Υ",
	"Upphi": "Φ",
	"Uppsi": "Ψ",
	"Upomega": "Ω",
};




export const map_super:{[name: string]:string} = {
	"(":  "⁽",
	")":  "⁾",
	"+":  "⁺",
	"-":  "⁻",
	"=":  "⁼",
	":":  "︓",
	";":  "︔",
	"<":  "˂",
	">":  "˃",
	"0":  "⁰",
	"1":  "¹",
	"2":  "²",
	"3":  "³",
	"4":  "⁴",
	"5":  "⁵",
	"6":  "⁶",
	"7":  "⁷",
	"8":  "⁸",
	"9":  "⁹",
	"a":  "ᵃ",
	"b":  "ᵇ",
	"c":  "ᶜ",
	"d":  "ᵈ",
	"e":  "ᵉ",
	"f":  "ᶠ",
	"g":  "ᵍ",
	"h":  "ʰ",
	"i":  "ⁱ",
	"j":  "ʲ",
	"k":  "ᵏ",
	"l":  "ˡ",
	"m":  "ᵐ",
	"n":  "ⁿ",
	"o":  "ᵒ",
	"p":  "ᵖ",
	"r":  "ʳ",
	"s":  "ˢ",
	"t":  "ᵗ",
	"u":  "ᵘ",
	"v":  "ᵛ",
	"w":  "ʷ",
	"x":  "ˣ",
	"y":  "ʸ",
	"z":  "ᶻ",
	"A":  "ᴬ",
	"B":  "ᴮ",
	"D":  "ᴰ",
	"E":  "ᴱ",
	"G":  "ᴳ",
	"H":  "ᴴ",
	"I":  "ᴵ",
	"J":  "ᴶ",
	"K":  "ᴷ",
	"L":  "ᴸ",
	"M":  "ᴹ",
	"N":  "ᴺ",
	"O":  "ᴼ",
	"P":  "ᴾ",
	"R":  "ᴿ",
	"T":  "ᵀ",
	"U":  "ᵁ",
	"V":  "ⱽ",
	"W":  "ᵂ",
};




export const map_sub =
{
	// "\\beta":  "ᵦ",
	// "\\rho":   "ᵨ",
	// "\\phi":   "ᵩ",
	// "\\gamma": "ᵧ",
	// "\\chi":   "ᵪ",
	"(":       "₍",
	")":       "₎",
	"+":       "₊",
	"-":       "₋",
	"=":       "₌",
	"0":       "₀",
	"1":       "₁",
	"2":       "₂",
	"3":       "₃",
	"4":       "₄",
	"5":       "₅",
	"6":       "₆",
	"7":       "₇",
	"8":       "₈",
	"9":       "₉",
	"a":       "ₐ",
	"e":       "ₑ",
	"h":       "ₕ",
	"i":       "ᵢ",
	"j":       "ⱼ",
	"k":       "ₖ",
	"l":       "ₗ",
	"m":       "ₘ",
	"n":       "ₙ",
	"o":       "ₒ",
	"p":       "ₚ",
	"r":       "ᵣ",
	"s":       "ₛ",
	"t":       "ₜ",
	"u":       "ᵤ",
	"v":       "ᵥ",
	"x":       "ₓ",
};


export const bar = {
	"a": "ā",
	"e": "ē",
	"g": "ḡ",
	"i": "ī",
	"o": "ō",
	"u": "ū",
	"A": "Ā",
	"E": "Ē",
	"G": "Ḡ",
	"I": "Ī",
	"O": "Ō",
	"U": "Ū",
}


export const dot = {
	"A": "Ȧ",
	"a": "ȧ",
	"B": "Ḃ",
	"b": "ḃ",
	"C": "Ċ",
	"c": "ċ",
	"D": "Ḋ",
	"d": "ḋ",
	"E": "Ė",
	"e": "ė",
	"F": "Ḟ",
	"f": "ḟ",
	"G": "Ġ",
	"g": "ġ",
	"H": "Ḣ",
	"h": "ḣ",
	"I": "İ",
	"M": "Ṁ",
	"m": "ṁ",
	"N": "Ṅ",
	"n": "ṅ",
	"O": "Ȯ",
	"o": "ȯ",
	"P": "Ṗ",
	"p": "ṗ",
	"R": "Ṙ",
	"r": "ṙ",
	"S": "Ṡ",
	"s": "ṡ",
	"T": "Ṫ",
	"t": "ṫ",
	"W": "Ẇ",
	"w": "ẇ",
	"X": "Ẋ",
	"x": "ẋ",
	"Y": "Ẏ",
	"y": "ẏ",
	"Z": "Ż",
	"z": "ż",
}


export const hat = {
	"a": "â",
	"A": "Â",
	"c": "ĉ",
	"C": "Ĉ",
	"e": "ê",
	"E": "Ê",
	"g": "ĝ",
	"G": "Ĝ",
	"i": "î",
	"I": "Î",
	"o": "ô",
	"O": "Ô",
	"s": "ŝ",
	"S": "Ŝ",
	"u": "û",
	"U": "Û",
	"w": "ŵ",
	"W": "Ŵ",
	"y": "ŷ",
	"Y": "Ŷ",
}



export const brackets = {
	// "left(": "(",
	// "left[": "[",
	// "left\\{": "\\{",
	// "right)": ")",
	// "right]": "]",
	// "right\\}": "\\}",
	// "left\\langle": "〈",
	// "right\\rangle": "〉",

	"left<": "〈",
	"right>": "〉",
	"langle": "〈",
	"rangle": "〉",
	"lvert": "|",
	"rvert": "|",
	"lVert": "‖",
	"rVert": "‖",
	"vert": "|",
	// "|": "‖",
	".": "",
	"/": "/",
	"Arrowvert": "‖",
	// "Downarrow": "⇓",
	// "Uparrow": "⇑",
	// "Updownarrow": "⇕",
	"Vert": "‖",
	"arrowvert": "⏐",
	// "backslash": "\\",
	"bracevert": "⎪",
	// "downarrow": "↓",
	"left\\gt": "⟩",
	"right\\gt": "⟩",
	"lbrace": "{",
	"lbrack": "[",
	// "lceil": "⌈",
	"lfloor": "⌊",
	"lgroup": "⟮",
	"llcorner": "⌞",
	"lmoustache": "⎰",
	"lparen": "(",
	"lrcorner": "⌟",
	"left\\lt": "⟨",
	"right\\lt": "⟨",
	"rbrace": "}",
	"rbrack": "]",
	// "rceil": "⌉",
	"rfloor": "⌋",
	"rgroup": "⟯",
	"rmoustache": "⎱",
	"rparen": ")",
	"ulcorner": "⌜",
	// "uparrow": "↑",
	// "updownarrow": "↕",
	"urcorner": "⌝",
}



export const mathbb = {
	" ": " ",
	"0": "𝟘",
	"1": "𝟙",
	"2": "𝟚",
	"3": "𝟛",
	"4": "𝟜",
	"5": "𝟝",
	"6": "𝟞",
	"7": "𝟟",
	"8": "𝟠",
	"9": "𝟡",
	"A": "𝔸",
	"B": "𝔹",
	"C": "ℂ",
	"D": "𝔻",
	"E": "𝔼",
	"F": "𝔽",
	"G": "𝔾",
	"H": "ℍ",
	"I": "𝕀",
	"J": "𝕁",
	"K": "𝕂",
	"L": "𝕃",
	"M": "𝕄",
	"N": "ℕ",
	"O": "𝕆",
	"P": "ℙ",
	"Q": "ℚ",
	"R": "ℝ",
	"S": "𝕊",
	"T": "𝕋",
	"U": "𝕌",
	"V": "𝕍",
	"W": "𝕎",
	"X": "𝕏",
	"Y": "𝕐",
	"Z": "ℤ",
	"a": "𝕒",
	"b": "𝕓",
	"c": "𝕔",
	"d": "𝕕",
	"e": "𝕖",
	"f": "𝕗",
	"g": "𝕘",
	"h": "𝕙",
	"i": "𝕚",
	"j": "𝕛",
	"k": "𝕜",
	"l": "𝕝",
	"m": "𝕞",
	"n": "𝕟",
	"o": "𝕠",
	"p": "𝕡",
	"q": "𝕢",
	"r": "𝕣",
	"s": "𝕤",
	"t": "𝕥",
	"u": "𝕦",
	"v": "𝕧",
	"w": "𝕨",
	"x": "𝕩",
	"y": "𝕪",
	"z": "𝕫",
}


export const mathscrcal = {
	"A": "𝓐",
	"B": "𝓑",
	"C": "𝓒",
	"D": "𝓓",
	"E": "𝓔",
	"F": "𝓕",
	"G": "𝓖",
	"H": "𝓗",
	"I": "𝓘",
	"J": "𝓙",
	"K": "𝓚",
	"L": "𝓛",
	"M": "𝓜",
	"N": "𝓝",
	"O": "𝓞",
	"P": "𝓟",
	"Q": "𝓠",
	"R": "𝓡",
	"S": "𝓢",
	"T": "𝓣",
	"U": "𝓤",
	"V": "𝓥",
	"W": "𝓦",
	"X": "𝓧",
	"Y": "𝓨",
	"Z": "𝓩",
}



export const mathfrak = {
	"a": "𝔞",
	"b": "𝔟",
	"c": "𝔠",
	"d": "𝔡",
	"e": "𝔢",
	"f": "𝔣",
	"g": "𝔤",
	"h": "𝔥",
	"i": "𝔦",
	"j": "𝔧",
	"k": "𝔨",
	"l": "𝔩",
	"m": "𝔪",
	"n": "𝔫",
	"o": "𝔬",
	"p": "𝔭",
	"q": "𝔮",
	"r": "𝔯",
	"s": "𝔰",
	"t": "𝔱",
	"u": "𝔲",
	"v": "𝔳",
	"w": "𝔴",
	"x": "𝔵",
	"y": "𝔶",
	"z": "𝔷",
	"A": "𝔄",
	"B": "𝔅",
	"C": "ℭ",
	"D": "𝔇",
	"E": "𝔈",
	"F": "𝔉",
	"G": "𝔊",
	"H": "ℌ",
	"I": "ℑ",
	"J": "𝔍",
	"K": "𝔎",
	"L": "𝔏",
	"M": "𝔐",
	"N": "𝔑",
	"O": "𝔒",
	"P": "𝔓",
	"Q": "𝔔",
	"R": "ℜ",
	"S": "𝔖",
	"T": "𝔗",
	"U": "𝔘",
	"V": "𝔙",
	"W": "𝔚",
	"X": "𝔛",
	"Y": "𝔜",
	"Z": "ℨ",
}
