// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  InlineStart = 1,
  InlineEnd = 2,
  DisplayStart = 3,
  DisplayEnd = 4,
  Dollar = 5,
  Program = 6,
  Text = 7,
  DollarInlineMath = 8,
  InlineMath = 9,
  DollarDisplayMath = 10,
  DisplayMath = 11
