// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {mathTokens} from "./math_tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!dQQOXOOOcOQO'#CdOhOSO'#CfOOOW'#Cj'#CjOOOW'#Ch'#ChQQOXOOOmOWO,59OOrOWO,59QOOOW-E6f-E6fOOOW1G.j1G.jOOOW1G.l1G.l",
  stateData: "|~OPPORQOTROVRO_RO~OXUO~OZVO~OQXO~OSYO~O_VXZ~",
  goto: "n_PPPPPPPP`P`PdPjTROTQTORWTTSOT",
  nodeNames: "⚠ InlineStart InlineEnd DisplayStart DisplayEnd Dollar Program Text DollarInlineMath InlineMath DollarDisplayMath DisplayMath",
  maxTerm: 15,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "&x~RWOYkYZ!^Ztku#Ok#O#P$g#P;'Sk;'S;=`$a<%lOkVtWVPXQZSOYkYZ!^Ztku#Ok#O#P#k#P;'Sk;'S;=`$a<%lOkT!eUVPZSOt!^u#O!^#O#P!w#P;'S!^;'S;=`#e<%lO!^T#OVVPZSOt!^tu!^u#O!^#O#P!w#P;'S!^;'S;=`#e<%lO!^T#hP;=`<%l!^V#tXVPXQZSOYkYZ!^Ztktuku#Ok#O#P#k#P;'Sk;'S;=`$a<%lOkV$dP;=`<%lk~$pXVPXQZSOYkYZ!^Ztktu%]u#Ok#O#P&Q#P;'Sk;'S;=`$a<%lOk~%hW_~VPXQZSOYkYZ!^Ztku#Ok#O#P#k#P;'Sk;'S;=`$a<%lOk~&]X_~VPXQZSOYkYZ!^Ztktuku#Ok#O#P#k#P;'Sk;'S;=`$a<%lOk",
  tokenizers: [0, 1, 2, mathTokens],
  topRules: {"Program":[0,6]},
  tokenPrec: 39
})
