import { LatexSuitePluginSettings } from "./settings";

export const EMPTY_SETTINGS: LatexSuitePluginSettings = {
	snippets: "",
	snippetVariables: "",

	// Basic settings
	snippetsEnabled: false,
	snippetsTrigger: "",
	snippetNextTabstopTrigger: "",
	snippetPreviousTabstopTrigger: "",
	suppressSnippetTriggerOnIME: false,
	suppressIMEWarning: false,
	removeSnippetWhitespace: false,
	autoDelete$: false,
	loadSnippetsFromFile: false,
	loadSnippetVariablesFromFile: false,
	snippetsFileLocation: "",
	snippetVariablesFileLocation: "",
	concealEnabled: false,
	concealRevealTimeout: 0,
	colorPairedBracketsEnabled: false,
	highlightCursorBracketsEnabled: false,
	mathPreviewEnabled: false,
	mathPreviewPositionIsAbove: false,
	mathPreviewCursor: "",
	mathPreviewBracketHighlighting: false,
	mathPreviewLivePreviewDisplay: false,
	autofractionEnabled: false,
	autofractionSymbol: "",
	autofractionBreakingChars: "",
	matrixShortcutsEnabled: false,
	taboutEnabled: false,
	taboutExitEquationOnlyOnEOL: false,
	taboutTrigger: "",
	autoEnlargeBrackets: false,
	autoEnlargeBracketsSpace: false,
	wordDelimiters: "",

	// Raw settings
	autofractionExcludedEnvs: "[]",
	matrixShortcutsEnvNames: "",
	matrixShortcutsMacroNames: "",
	taboutClosingSymbols: "",
	autoEnlargeBracketsTriggers: "",
	forceMathLanguages: "",
	snippetDebug: "off",
	vimEnabled: false,
	vimSelectMode: "",
	vimVisualMode: "",
	vimMatrixEnter: "",
	snippetRecursion: 0,
	snippetIMEVersion: false,
	highlightDollarEnabled: false,
	excalidrawSupportEnabled: false,
	logLevel: "off",
}
