{
	"${AUTO_BACKSLASH}": "{GREEK}|{SYMBOLS}|{SEPERATORS}|{FUNCTIONS}|{TRIGONOMETRIC}|{HYPOBOLIC_TRIG}",
	"${AUTO_SPACE}": "{SEPERATORS}|{GREEK}|{SYMBOLS}|{MORE_SYMBOLS}|{TRIGONOMETRIC}|{HYPOBOLIC_TRIG}",
	"${OVERWRITE_AUTO_SPACE}": "({TRIGONOMETRIC})h|(in)t",
	"${AUTO_LETTER_SUBSCRIPT}": "[a-zA-Z]|{GREEK}|{FUNCTIONS}",
	"${GREEK}": "{GREEK}",
}